// ==UserScript==
// @name         Slut NOT Drop
// @version      1.0
// @description  AutoClicker for Slut TON Drop
// @author       Emin M @emin.mir
// @homepage     https://t.me/crypto_world_aze
// @match        https://zapn.digital/*
// @icon         https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRBfD3Vv-jzGzJ9M_UBA9K-XqS7bG_VfhqNnbOyViPJhl-pLCP
// @downloadURL  https://github.com/oliver134/slut/raw/main/Slut NOT Drop Auto clicker.user.js
// @updateURL    https://github.com/oliver134/slut/raw/main/Slut NOT Drop Auto clicker.user.js
// @grant        none
// ==/UserScript==
!function(){"use strict";let e=!1,t,o=0;const n="_ass_125s5_72",a="_life_text_125s5_215",c=document.createElement("button");function l(){e?i():r()}function r(){e=!0,c.innerHTML="Stop",c.style.backgroundColor="#8B0000",t=setInterval(s,1e3)}function i(){e=!1,c.innerHTML="Play",c.style.backgroundColor="#8B0000",clearInterval(t)}function s(){const t=document.querySelector(`.${n}`),c=document.querySelector(`.${a}`);if(c&&"0"===c.innerText){const n=Math.random()*(3e4-5e3)+5e3;return clearInterval(t),void setTimeout((()=>{e&&r()}),n)}if(t){const n=t.getBoundingClientRect(),a=Math.random()*n.width+n.left,c=Math.random()*n.height+n.top,l=new MouseEvent("click",{bubbles:!0,cancelable:!0,clientX:a,clientY:c});t.dispatchEvent(l),o++,o>=100&&(o=0,clearInterval(t),setTimeout((()=>{e&&r()}),Math.random()*(3e4-5e3)+5e3))}}c.innerHTML="Play",c.style.position="fixed",c.style.bottom="10px",c.style.right="10px",c.style.padding="10px 20px",c.style.fontSize="16px",c.style.backgroundColor="#8B0000",c.style.color="#fff",c.style.border="none",c.style.borderRadius="5px",c.style.cursor="pointer",c.style.boxShadow="0 4px 6px rgba(0, 0, 0, 0.1)",c.style.zIndex="1000",document.body.appendChild(c),c.addEventListener("click",l);const d=document.createElement("div");d.style.position="fixed",d.style.top="0",d.style.left="50%",d.style.transform="translateX(-50%)",d.style.zIndex="9999",d.style.backgroundColor="#2c2c2c",d.style.opacity="0.6",d.style.padding="3px 12px",d.style.borderRadius="10px",d.style.boxShadow="0px 4px 15px rgba(0, 0, 0, 0.5)",document.body.appendChild(d);const y=document.createElement("div");y.style.display="inline-block",y.style.marginRight="10px";const p=document.createElement("a");p.href=atob("aHR0cHM6Ly90Lm1lL2NyeXB0b193b3JsZF9hemU="),p.innerHTML=atob("Rm9yIG1vcmUgaW5mbyBjbGljayBoZXJlOg=="),p.style.color="snow",p.style.fontWeight="bold",p.style.fontSize="9px",p.style.marginBottom="5px",p.style.alignItems="center",p.style.textDecoration="none";const f=document.createElement("img");f.src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/telegram/telegram.png",f.style.width="15px",f.style.height="15px",f.style.marginRight="5px",f.addEventListener("click",(function(){window.location.href=atob("aHR0cHM6Ly90Lm1lL2NyeXB0b193b3JsZF9hemU=")}));const m=document.createElement("a");m.href=atob("aHR0cHM6Ly90Lm1lL2NyeXB0b193b3JsZF9hemU="),m.innerHTML=atob("Q3J5cHRvIFdvcmxkCg=="),m.style.color="white",m.style.fontWeight="bold",m.style.fontSize="14px",m.style.textDecoration="none";const u=document.createElement("div");u.style.display="flex",u.style.alignItems="center",u.appendChild(f),u.appendChild(m),y.appendChild(p),y.appendChild(u),d.appendChild(y)}();
